/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentContactUs: typeof import('./src/components/ComponentContactUs.vue')['default']
    ComponentFooter: typeof import('./src/components/ComponentFooter.vue')['default']
    ComponentHeader: typeof import('./src/components/ComponentHeader.vue')['default']
    ComponentPagination: typeof import('./src/components/ComponentPagination.vue')['default']
    CssBackgroundBlack: typeof import('./src/components/CssBackgroundBlack.vue')['default']
    CssBackgroundWhite: typeof import('./src/components/CssBackgroundWhite.vue')['default']
    LibComponentTyped: typeof import('./src/components/LibComponentTyped.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiCheckbox: typeof import('./src/components/UiCheckbox.vue')['default']
    UiDropdownCheckbox: typeof import('./src/components/UiDropdownCheckbox.vue')['default']
    UiInputSearch: typeof import('./src/components/UiInputSearch.vue')['default']
    UiSelect: typeof import('./src/components/UiSelect.vue')['default']
  }
}
