/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/equipment/': RouteRecordInfo<'/equipment/', '/equipment', Record<never, never>, Record<never, never>>,
    '/equipment/detail': RouteRecordInfo<'/equipment/detail', '/equipment/detail', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/information/': RouteRecordInfo<'/information/', '/information', Record<never, never>, Record<never, never>>,
    '/information/detail': RouteRecordInfo<'/information/detail', '/information/detail', Record<never, never>, Record<never, never>>,
    '/service/': RouteRecordInfo<'/service/', '/service', Record<never, never>, Record<never, never>>,
    '/train/material': RouteRecordInfo<'/train/material', '/train/material', Record<never, never>, Record<never, never>>,
    '/train/video': RouteRecordInfo<'/train/video', '/train/video', Record<never, never>, Record<never, never>>,
  }
}
